name: MSVC Build
on: workflow_dispatch

env:
  BUILD_CONFIGURATION: Game__Shipping__Win64

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup github SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.UEPSEUDO_SSH_KEY }}
        known_hosts: unnecessary

    - name: Checkout SFV
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0 # needed to get commits since last tag
        ssh-key: ${{ secrets.UEPSEUDO_SSH_KEY }}
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" ..
        msbuild /p:Configuration=${{env.BUILD_CONFIGURATION}} .\StriveFrameData\StriveFrameData.sln
        msbuild /p:Configuration=${{env.BUILD_CONFIGURATION}} .\RE-UE4SS\UE4SS\proxy_generator\proxy\proxy.sln

    - name: Package
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir result\ue4ss\StriveFrameViewer\dlls
        cp .\build\StriveFrameData\${{env.BUILD_CONFIGURATION}}\StriveFrameData.dll .\result\ue4ss\StriveFrameViewer\dlls\main.dll

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: StriveFrameViewer
        path: ${{github.workspace}}\result\
        if-no-files-found: error


        
    