name: MSVC Build

on:
  push:
    branches: [ "master" ]
    paths:
      - '**/build.yml'

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout SFV
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" ..
        msbuild /p:Configuration=${{env.BUILD_CONFIGURATION}} .\StriveFrameData\StriveFrameData.sln
        msbuild /p:Configuration=${{env.BUILD_CONFIGURATION}} .\RE-UE4SS\UE4SS\proxy_generator\proxy\proxy.sln

    - name: Package
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir result\Mods\StriveFrameViewer
        cp .\build\StriveFrameData\Game__Debug__Win64\StriveFrameData.dll .\result\Mods\StriveFrameData\main.dll
        cp .\build\Output\Game__Debug__Win64\proxy\bin\dwmapi.dll .\result\dwmapi.dll
        cp .\build\Output\Game__Debug__Win64\UE4SS\bin\UE4SS.dll .\result\UE4SS.dll
        cp .\prereqs\mods.txt .\result\Mods\mods.txt
        cp .\prereqs\UE4SS-settings.ini .\result\UE4SS-settings.ini

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: StriveFrameData
        path: ${{env.GITHUB_WORKSPACE}}/result
        if-no-files-found: error


        
    